CREATE DATABASE IF NOT EXISTS base_almacen;

USE base_almacen;


CREATE TABLE IF NOT EXISTS categoria(
  id_categoria INT PRIMARY KEY AUTO_INCREMENT,
  categoria VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS centro (
  id_centro INT PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  direccion varchar(100) NOT NULL,
  jurisdiccion varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS financiamiento (
  id_financiamiento INT PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  descripcion varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS licitacion (
  id_licitacion INT PRIMARY KEY AUTO_INCREMENT,
  licitacion varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS partida (
  id_partida INT PRIMARY KEY AUTO_INCREMENT,
  clave_federal varchar(10) NOT NULL,
  nombre varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS programa (
  id_programa INT PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS proveedor (
  id_proveedor INT PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  rfc varchar(20) NOT NULL,
  telefono varchar(10) NOT NULL,
  correo varchar(50) NOT NULL,
  direccion varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS unidadaplicativa (
  id_unidad  INT PRIMARY KEY AUTO_INCREMENT,
  tipo_unidad varchar(130) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS producto (
  id_producto INT PRIMARY KEY AUTO_INCREMENT,
  clave text NOT NULL,
  id_unidad INT,
  nombre text NOT NULL,
  descripcion text NOT NULL,
  id_categoria INT,
  serie text NOT NULL,
  FOREIGN KEY (id_unidad) REFERENCES unidadaplicativa(id_unidad),
  FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS usuario (
  id_usuario  INT PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(255) NOT NULL,
  apellidos varchar(255) NOT NULL,
  usuario varchar(50) NOT NULL,
  password varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS contrato (
  id_contrato  INT PRIMARY KEY AUTO_INCREMENT,
  clave varchar(255) NOT NULL,
  doct varchar(255) NOT NULL,
  id_producto INT,
  id_financiamiento INT,
  id_centro INT,
  id_programa INT,
  id_partida INT,
  id_proveedor INT,
  id_licitacion INT,
  precio FLOAT NOT NULL,
  cantidad INT NOT NULL,
  iva varchar(5) NOT NULL,
  fecha date,
  importe varchar(255) NOT NULL,
  existencia INT NOT NULL,
  FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
  FOREIGN KEY (id_financiamiento) REFERENCES financiamiento(id_financiamiento),
  FOREIGN KEY (id_centro) REFERENCES centro(id_centro),
  FOREIGN KEY (id_programa) REFERENCES programa(id_programa),
  FOREIGN KEY (id_partida) REFERENCES partida(id_partida),
  FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor),
  FOREIGN KEY (id_licitacion) REFERENCES licitacion(id_licitacion)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS contrata (
  id_contrata  INT PRIMARY KEY AUTO_INCREMENT,
  id_contrato INT,
  id_producto INT,
  precio FLOAT NOT NULL,
  cantidad INT NOT NULL,
  fecha date,
  importe varchar(255) NOT NULL,
  existencia int(10) NOT NULL,
  FOREIGN KEY (id_contrato) REFERENCES contrato(id_contrato),
  FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS remision (
  id_remision  INT PRIMARY KEY AUTO_INCREMENT,
  id_contrata INT,
  fecha date NOT NULL,
  caducidad date NOT NULL,
  lote varchar(255) NOT NULL,
  cantidad INT NOT NULL,
  existencia int(10) NOT NULL,
  FOREIGN KEY (id_contrata) REFERENCES contrata(id_contrata)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO financiamiento (id_financiamiento, nombre, descripcion) VALUES
(7, 'AFASPE RAMO 12 2019', ''),
(8, 'CENAPRECE', ''),
(9, 'DIRECCION DE PREVENCION Y PROMOCION A LA SALUD', ''),
(10, 'SEGURO POPULAR', ''),
(11, 'PROGRAMA FEDERAL DE PLANIFICACION Y ANTICONCEPCION', ''),
(12, 'FASSA 2019', ''),
(13, 'CENTRO NACIONAL DE EQUIDAD DE GENERO Y SALUD REPRO', ''),
(14, 'FEDERAL', ''),
(15, 'FONDEN', ''),
(16, 'CRESCA-CONADIC-OAXACA 2019', ''),
(17, 'SEGURO MEDICO SIGLO XXI', ''),
(18, 'COFEPRIS-CETR-2019', ''),
(19, 'COMPRA EMERGENTE', ''),
(20, 'ORVI', ''),
(21, 'U013 ATENCION A LA SALUD Y MEDICAMENTOS GRATUITOS ', ''),
(22, 'PROSPERA 2018', ''),
(23, 'AFASPE RAMO 12 2020', ''),
(24, 'FONDEN 2020', ''),
(25, 'COVID', 'COVID-19/2020'),
(26, 'INSABI', 'PRESTACION GRATUITA DE SERVICIOS DE SALUD, MEDICAMENTOS Y DEMAS INSUMOS ASOCIADOS 2020.'),
(27, 'S/F', 'SIN FUENTE DE FINANCIAMIENTO'),
(28, 'CENAPRECE 2020', 'CENAPRECE 2020'),
(29, 'INSABI SEGURO MEDICO SIGLO XXI 2020', ''),
(30, 'FONDO DE PROTECCION CONTRA GASTOS CATASTROFICOS SS', 'FONDO DE PROTECCION CONTRA GASTOS CATASTROFICOS SSO'),
(31, 'INSABI PRESTACION GRATUITA DE SERVICIOS DE SALUD, ', ''),
(32, 'CENTRO NACIONAL DE PROGRAMAS PREVENTIVOS Y CONTROL', ''),
(33, 'FASSA CAPITAL 2020', ''),
(34, 'INSABI U013 VERTIENTE 2', ''),
(35, 'FONDEN 2021', ''),
(36, 'APORTACION SOLIDARIA ESTATAL LIQUIDA 2021', ''),
(37, 'INSABI 2021', ''),
(38, 'CRESCA-CONADIC 2020', ''),
(39, 'FASSA 2021', 'FONDO DE APORTACIÓN PARA LOS SERVICIOS DE SALUD.'),
(40, 'CENAPRECE 2021', 'CENAPRECE 2021'),
(41, 'PRESTACION GRATUITA DE SERVICIOS DE SALUD, MEDICAM', 'PRESTACION GRATUITA DE SERVICIOS DE SALUD, MEDICAMENTOS Y DEMAS INSUMOS ASOCIADOS PARA LAS PERSONAS '),
(42, 'INSABI U013 VERTIENTE 2', 'PROGRAMA U013 ATENCION A LA SALUD Y MEDICAMENTOS GRATUITOS PARA LA POBLACION SIN SEGURIDAD SOCIAL LA'),
(43, 'AFASPE RAMO 12 2021', ''),
(44, 'ADJUDICACION DIRECTA', 'ADJUDICACION DIRECTA'),
(45, 'ASIGNACION PARA INVERSION MEDIANTE EL REPORTE PRES', ''),
(46, 'CRESCA-CONADIC-OAX-001/2021', 'CRESCA-CONADIC-OAX-001/2021'),
(47, 'BEBGZ2121 ”SUBSIDIO PARA EL FORTALECIMENTO PREFERE', ''),
(48, 'INSABI 2021 (PRESTACION GRATUITA DE SERVICIOS DE S', ''),
(49, 'FONDO DE APORTACIONES PARA LOS SERVICIOS DE SALUD ', ''),
(50, 'AEAAA0421', ''),
(51, 'ASIGNACION ORDINARIA DE OPERACION', ''),
(52, 'SUBSIDIO PARA EL FORTALECIMENTO PREFERENTEMENTE DE', ''),
(53, 'CENTRO NACIONAL PARA LA SALUD DE LA INFANCIA Y LA ', ''),
(54, 'ASIGNACION ORDINARIA DE OPERACION 2021', 'ASIGNACION ORDINARIA DE OPERACION 2021'),
(55, 'INSABI PRESTACIÓN GRATUITA DE SERVICIOS DE SALUD, ', ''),
(56, 'FASSA 2022', ''),
(57, 'BEBGZ2121 \"SUBSIDIO PARA EL FORTALECIMIENTO PREFER', ''),
(58, 'BECDH0121 INSABI', ''),
(59, 'BECDH0121 INSABI, PRESTACION GRATUITA DE SERVICIOS', ''),
(60, 'INSABI 2022', '');


INSERT INTO licitacion (id_licitacion, licitacion) VALUES
(3, 'SIN LICITACION'),
(5, 'LA-050GYR047-045-2018'),
(6, 'AA-050GYR047-E71-2018'),
(7, 'LA-050GYR047-E44-2018'),
(8, 'LA-012000991-E82-2019'),
(9, 'LA-050GYR047-E45-2018'),
(10, 'LA-050GYR047-E63-2018'),
(11, 'LA-050GYR047-E64-2018'),
(12, 'AA-050GYR047-E70-2018'),
(13, 'LA-050GYR047-045-2018'),
(14, 'L.P.I CAD41-III-CAAS-SESION EXXT 19/2019'),
(15, 'LA-012000991-E221-2019'),
(16, 'BOLETIN-BDE-001-2020.'),
(17, 'LA-012L00001-02-2020'),
(18, 'IA-920042950-E7-2021'),
(19, 'IA-920042950-E11-2021'),
(20, 'ICTP-IA920042950- E10-2021'),
(21, 'IA-920042950-E7-2021'),
(22, 'LPE-SA-SS-0027-11/2021'),
(23, 'LPE-SA-SS-0029-11/2021'),
(25, 'LA-920042950-E1-2021');
